### ISSUE TITLE
Virtual Environments Linux/Windows

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#108]
(See previous: #101 and #55 )

#### `bash` tools for `venv`
For all of htese currently, `/usr/local/share/venv/` is default
- `vbuild`: set up a new virtual env (replace old one if it exists)
- `venv`: load an existing venv
- `vlist`: list all venvs in the local stockhouse 

#### Installation
Get venv going on linux:
```
# install the venv package sitewide
apt install python3.12-venv
# Was (not proper): sudo python3.9 -m pip install virtualenv
# create a 
cd /usr/local/share/
mkdir venv
sudo chgrp allmodelers venv
sudo chmod g+w venv
cd venv/
# create the python 3.10 env (actually ended up being 3.9+ but ok)
sudo apt install python3.9-dev
python3.9 -m virtualenv hsp2dev_py10
# As of Ubuntu 24 with python 3.12 use venv
python3.12 -m venv hsp2dev_py13
chgrp allmodelers hsp2dev_py10 -Rf
chmod g+w hsp2dev_py10/* -Rf
cd /opt/model/HSPsquared/
source /usr/local/share/venv/hsp2dev_py10/bin/activate
# 2 ways to use pip:
# called as direct pip install
pip3.9 install .
# or called as python module
python3 -m pip install .

# then run as per normal
rm PL3_5250_0001.h5
hsp2 import_uci PL3_5250_0001.uci PL3_5250_0001.h5
hsp2 run PL3_5250_0001.h5

```
#### Add a shortcut to activate env
- This is in linux, the path is long
- Create file in a local path exec dir like `/home/rob/.local/bin/py312` with contents:
   - `#!/bin/bash`
   - `source /usr/local/share/venv/hsp2dev_py10/bin/activate`
- Activate with `. py312` (must precede script name with period to get loaded into current shell)
- Note: install ruff and pre-commit to insure compatibility with changes from respec team #118

#### New environments need new package installs
- When you first activate a new environment with a new python, you will need to install all your libs.
   - Unless of course, you are installing `hsp2` via `pip` which will install everything that you need, and insure that the versions are correct.
- Install a specific package version like so: `python3 -m pip install pandas==3.0.0`

```
python -m pip install numba
python -m pip install typed
python -m pip install numpy
```

### Windows
- Official docs here: https://code.visualstudio.com/docs/python/environments

#### Manually Adding an Interpreter and Environment
- Ctrl-P brings up search.  Type `>` to get system level stuff, type "python: 
<img width="742" height="69" alt="Image" src="https://github.com/user-attachments/assets/d454a725-65d2-45f2-9207-762e7982e5a9" />
- select "select at workspace level" to browse
<img width="797" height="260" alt="Image" src="https://github.com/user-attachments/assets/e689f586-b614-4729-bc38-f994d0c8ef86" />

- Must have C++ tools installed, and after update to VScode reinstall from Extensions:
   - Note the base C/C++ extension had to be installed on VPN (maybe just coincidence?)
<img width="1158" height="364" alt="Image" src="https://github.com/user-attachments/assets/b41eb72a-2817-4917-9b4c-88e3ad24d0c0" />

- Set up python 13 venv
   - note: set a custom default-timeout parameter due to network latency
   - done with powershell this time

```
# install the necessary virtual environment modules
C:\Users\faw18626\AppData\Local\Programs\Python\Python313\python.exe  -m pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --user virtualenv --default-timeout=100

# create the virtual environment
cd "C:\Users\faw18626\virtualenvs"
C:\Users\faw18626\AppData\Local\Programs\Python\Python313\python.exe -m virtualenv hsp2dev_py313

# Activate the new env
./hsp2dev_py313/Scripts/activate 
# in bash use: 
source hsp2dev_py313/Scripts/activate

# install hsp2
cd C:\usr\local\home\git\HSPsquared
# in bash use: 
cd /c/usr/local/home/git/HSPsquared
python -m pip install . --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --default-timeout=100

```

### Activate Existing Env in GitBash
```
# Activate the new env
source /c/Users/faw18626/virtualenvs/hsp2dev_py313/Scripts/activate
```

#### Run without numba (for debugging)
- `NUMBA_DISABLE_JIT=1 hsp2 run test10specl.h5`

#### `vbuild`
```
#!/bin/bash
# create/replace a virtual environment
# this should be called with the `. vbuild ...`
pbuild_venv="py312" # this just allows us to actually do this since python without venv throws error
pexec="python3.12" # this determines the version of python
venv_root="/usr/local/share/venv"
if [ $# -lt 1 ]; then
  echo "Use: vbuild env_name [python_exec=$pexec] [pbuild_venv_scr=$pbuild_venv] [venv_root=$venv_root]"
  return
fi
pdir=$PWD
env_name=$1
if [ $# -gt 1 ]; then
  pexec=$2
fi
if [ $# -gt 2 ]; then
  pbuild_venv=$3
fi
if [ $# -gt 3 ]; then
  venv_root=$4
fi
deactivate # get out of whatver you are in
# py 3.9 had "virtualenv" not "venv"
vmod="venv"
if [[ $pexec == *"3.9"* ]]; then
  vmod="virtualenv"
fi
if [[ $pexec == *"3.14"* ]]; then
  vmod="virtualenv"
fi
. $pbuild_venv # build with known OK python
echo "cd $venv_root"
cd $venv_root
echo "rm -Rf $env_name"
rm -Rf $env_name
echo "$pexec -m $vmod $env_name"
$pexec -m $vmod $env_name
deactivate # leave the building env
source $venv_root/${env_name}/bin/activate
cd $pdir
pv=`python3 --version`
echo "Built venv $1 with $pv"
echo "Be sure to execute: 'rm -Rf build' in your source directory"
```
#### `vlist`
```
#!/bin/bash
# list all venvs
venv_root="/usr/local/share/venv"
ls $venv_root -lhrt

```

# `venv`
```
#!/bin/bash
# list all venvs
venv_root="/usr/local/share/venv"
source $venv_root/${1}/bin/activate
(
```

**Comment by rburghol** [comment]
#### Main version python 3.12
- See notes on reinstalling `pre-commit` for `ruff` after this at https://github.com/HARPgroup/HSPsquared/issues/118#issuecomment-3702720455
```
sudo apt install python3.12 python3.12-devel
# As of Ubuntu 24 with python 3.12 use venv?  This is wierd. Since it does NOT work in python 3.14
python3.12 -m venv hsp2dev_py13
```

#### Setting a testing version of 3.10 on deq3:
- First, enabled deadsnakes repo: https://github.com/HARPgroup/vahydro/issues/1086
```
sudo apt install python3.10
python3.10 -m pip install virtualenv
cd /usr/local/share/venv
python3.10 -m virtualenv hsp2dev_py10
cp ~/.local/bin/py312 ~/.local/bin/py310
# edit py310 to use python 3.10
```
#### For a testing version of 3.9 had to add distutils in the `apt` portion
- `sudo apt-get install python3.9 python3.9-distutils`
- Then follow above `python 3.9 -m pip install virtualenv`
- However it never succeeded in running/compiling.
   - tried to install `hsp2` with `--no-binary :all:` option: `pip install --no-binary :all: .`
   - due to older stuff having compatibility problems.
   - no dice

**Comment by rburghol** [comment]
#### Testing version python 3.14 on deq3
- Note: installing 3.14-dev eliminates pip install error for hsp2  `./meson.build:44:2: ERROR: Problem encountered: Cannot compile `Python.h`. Perhaps you need to install python-dev|p`
- Note: error 2 was for liblz02, manually installed with `sudo apt install liblzo2-dev` error was `/tmp/lzo_version_datexc61jqpc.c:1:10: fatal error: lzo/lzo1x.h: No such file or directory`
- Note: manually installed `blosc` for python
```
sudo apt install python3.14
sudo apt install python3.14-dev
python3.14 -m pip install virtualenv
cd /usr/local/share/venv
# This fails in 3.14 even though it was needed in 3.12?!?
#python3.14 -m venv hsp2dev_py14
python3.14 -m virtualenv hsp2dev_py14
# added a venv starter script py314 from py312
. py314
sudo apt install liblzo2-dev 
python3.14 -m pip install blosc
# tables had error in blosc above that did not resolve with manual blosc2 install.
# tried:
python3.14 -m pip install --no-binary :all: tables

cd /opt/model/HSPsquared
pip install .
```

**Comment by rburghol** [comment]
Special pandas 3.0.0 virtual env setup for hsp2:
```
cd /usr/local/share/venv/
rm -Rf pandas3
python3.12 -m venv pandas3
python3 -m pip install pandas==3.0.0
```

**Comment by rburghol** [comment]
Python 3.15 on Ubuntu 26.04 (see sysadmin page for install tips https://github.com/HARPgroup/vahydro/issues/1086 )
```
cd /usr/local/share/
sudo mkdir venv
sudo chgrp allmodelers venv
sudo chmod g+w venv
python3.15 -m venv hsp2dev_py15

cd /opt/model/HSPsquared
source /usr/local/share/venv/hsp2dev_py15/bin/activate

# wheel had error for python 3.15:
pip install wheel --no-binary :all:
python3 -m pip install .
python3 -m pip install build

```
